config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "flats#index"
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
  validates :name, :address, :price_per_night, :number_of_guests, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController

  def index
    @flats = Flat.all
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to root_path, status: :see_other
    else
      render :new, status: :unprocessable_entity
    end
  end


  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<div class="container p-3">
  <h1>All our Flats (<%= @flats.all.length %>)</h1>

  <% @flats.each do |flat| %>

    <div class="d-inline-flex">
      <div class=" card m-2" style="width: 18rem;">
        <div class="card-body" style="background-color: rgb(248, 249, 250);">
          <h5 class="card-title"><%= flat.name %></h5>
          <h6 class="card-subtitle mb-2 text-muted"><%= flat.address %></h6>
          <span class="pe-2"><i class="fa-solid fa-user-group"></i> <%= flat.number_of_guests %></span>
          <span><i class="fa-solid fa-dollar-sign"></i> <%= flat.price_per_night %></span>
        </div>
        <a href="#" class="card-link card-body">Card link</a>
      </div>
    </div>

  <% end %>


</div>

app/views/flats/new.html.erb
<div class="container p-3">
  <%= simple_form_for @flat do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <%= f.input :price_per_night %>
    <%= f.input :number_of_guests %>
    <%= f.button :submit %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar bg-light">
      <div class="container-fluid">
        <a class="navbar-brand">Simple Airbnb</a>
        <button class="btn btn-outline-primary"><%= link_to "Add flat", new_flat_path %></button>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>